---
galaxy_info:
  author: Matthew Pontes
  description: Install rbenv and ruby on CentOS 7.  Based on Debian/Ubuntu role by Jarno Keskikangas.
  company: Leonidas
  license: MIT
  min_ansible_version: 1.4

  platforms:
  - name: EL
    versions:
     - 7

  categories:
  - development
  - packaging
  - web

dependencies: []
