---    
- name: Download the Kibana tarball
  command: curl -O https://download.elasticsearch.org/kibana/kibana/kibana-3.0.1.tar.gz
  #mode=0644 cent6.6
  args:
    chdir: /home/vagrant/
    creates: /home/vagrant/kibana-3.0.1

- name: Extract the Kibana archive
  unarchive: src=/home/vagrant/kibana-3.0.1.tar.gz dest=/home/vagrant/ copy=no
  # mode=0755

- name: Configure Kibana
  template: src=config.js.j2 dest=/home/vagrant/kibana-3.0.1/config.js #mode=0644 owner=root group=root mode=0644

- name: Copy Kibana installation into a new directory - create directory
  sudo: yes
  #command: mkdir -p /var/www/kibana3
  command: mkdir -p /usr/share/nginx/kibana3

- name: Copy Kibana installation into the new directory
  raw: sudo cp -R /home/vagrant/kibana-3.0.1/* /usr/share/nginx/kibana3/
  #apache:
  #raw: sudo cp -R /home/vagrant/kibana-3.0.1/* /var/www/kibana3/

- name: Create a Kibana login
  sudo: yes
  htpasswd:
    #path: /etc/httpd/conf.d/kibana-htpasswd
    path: /etc/nginx/conf.d/kibana.myhost.org.htpasswd
    name: vagrant
    password: vagrant
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Configure Kibana for nginx
  sudo: yes
  template: src=nginx_kibana.conf.j2 dest=/etc/nginx/conf.d/default.conf     #owner=root group=root mode=0644 
  notify:
    - restart nginx
    - restart elasticsearch