---
- name: Create a yum repository for Logstash
  sudo: yes
  template: src=logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo # owner=root group=root mode=0644

- name: Install Logstash
  sudo: yes
  yum: name=logstash-1.4.2 state=present

- name: Start Logstash and enable on boot
  service: name=logstash state=started enabled=yes

- name: Generate SSL Certificate and key pair
  sudo: yes
  command: openssl req -x509 -batch -nodes -days 3650 -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt
  args:
    chdir: /etc/pki/tls/

- name: Create Logstash Input Configuration file
  sudo: yes
  template: src=01-lumberjack-input.conf.j2 dest=/etc/logstash/conf.d/01-lumberjack-input.conf #owner=root group=root mode=0644

- name: Create a configuration file to filter syslog messages
  sudo: yes
  template: src=10-syslog.conf.j2 dest=/etc/logstash/conf.d/10-syslog.conf #owner=root group=root mode=0644

- name: Create a configuration file to filter output
  sudo: yes
  template: src=30-lumberjack-output.conf.j2 dest=/etc/logstash/conf.d/30-lumberjack-output.conf #owner=root group=root mode=0644 
  notify:
    - restart logstash

- name: Store a copy of the SSL Certificate to distribute to nodes
  sudo: yes
  fetch: src=/etc/pki/tls/certs/logstash-forwarder.crt dest=roles/mjp182.logstash/files/logstash-forwarder.crt flat=yes