---
galaxy_info:
  author: Matthew Pontes
  description: Role to install Logstash as part of the ELK stack
  company: your company (optional)
  license: license (BSD, MIT)
  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  categories:
  - monitoring

dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
